### ISSUE TITLE
Add a method to load an audio file

### ISSUE THREAD

**Issue by ludelafo** [2find/stereo#12]
The library should be able to load an audio file to be played.

I see the following methods:
- `void load(String)` - load the audio file from a string representing the URI to the file
- `void load(URI)` - load the audio file from an URI pointing to the file
- `void load(AudioFile)` - load the audio file directly from an audio file

The two firsts methods would call the later one to avoid redundancy.

These methods should throw an exception if the audio file can't be loaded.

**Comment by ludelafo** [comment]
I was wondering if the `load` and `unload` methods were needed if we changed the `play` method to accept string, URI or AudioFile parameters. What would be the benefits to have these two methods?

**Comment by faku99** [comment]
IMO, they are needed because we don't want for sure to play a file directly after it has been loaded.

Having a `load` method allows loading a file and let the choice of playing it to the user.

Concerning the `unload` method, I still have my doubts about its purpose. It will be clearer in the future.

**Comment by faku99** [comment]
Do we really need to offer multiple parameters? I think one specifying the file's URI is enough. Documentation about the `Uri` class is available [here](https://www.dartlang.org/guides/libraries/library-tour#uris).

Here are my thoughts:
* The `String` parameter is useless since it is a URI itself.
* The `AudioFile` parameter is also useless as one of its members is the URI of the audio file. So when calling the `load` method, the developer simply has to pass `audiofile.uri` as the parameter.

What do you think about offering only a `load(URI)` method?

**Comment by faku99** [comment]
As the commit above states, I started to work on this method.

* The method signature is now : `Future load(String uri)`.
* It now throws a `StereoFileNotPlayableException` exception if the file pointed by the `uri` parameter is not playable.

The platform-specific code is implemented only for iOS at the moment. I will begin working on the Android part as soon as I can.
